---
abstract: 'Binary Search a sorted array with XS routines.'
author:
  - 'David Oswald <davido [@at] cpan [d.o.t.] org>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.62
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.74, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-BinarySearch-XS
no_index:
  directory:
    - t
    - inc
provides:
  List::BinarySearch::XS:
    file: lib/List/BinarySearch/XS.pm
    version: 0.04
requires:
  perl: 5.008000
version: 0.04
